version: '3.8'

services:
  blog-summarizer:
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - HF_HOME=/home/jovyan/work/hf_cache
    restart: unless-stopped

    networks:
      - network_apps

volumes:
  huggingface_cache:

networks:
  network_apps:
    external: true
